### ISSUE TITLE
Auth token security

### ISSUE THREAD

**Issue by VectorXz** [SlothPete7773/line-sundaycodelab-covid-bot#1]
https://github.com/SlothPete7773/line-sundaycodelab-covid-bot/blob/fa62e83088a1ef4c6f497d7714a6f6c1c94b909c/functions/index.js#L49

You may want to remove auth token here for security reason as this is public repo, and anyone can see this.

It would be nice if you re-issued your token.

As my advice, you may put your access tokens in .env file and exclude them in .gitignore.

**Comment by SlothPete7773** [comment]
Thanks for the heads up! I will fix it.
